### ISSUE TITLE
shortener

### ISSUE THREAD

**Issue by 7zxkv** [deivastra/piped-watch#2]
Hello,

It seems to me that youtube shortcut links like https://youtu.be/xxxxxx don't work.if it could be integrated, best regards

edit: well apparently it's when there's extra useless info behind the link. if the link is clean it works. 
example:  https://youtu.be/iqNusdhQ1fA?si=sMEGkN81HXVd7FbD doesn't work
whereas https://youtu.be/iqNusdhQ1fA work.
maybe there should be a condition to avoid this kind of classic case when you click on a link via a site like facebook, etc. filled with useless meta data.

**Comment by D01B0EB** [comment]
Hello, I confirm the problem.
In the next few hours I will publish fixed (2.0.2) version. + Review the extension on the chrome web store usually takes several hours.
Thanks for feedback.

**Comment by D01B0EB** [comment]
The Chrome web store published 2.0.2 version. Could you test new version? If the issue fixed, I will close.

**Comment by 7zxkv** [comment]
hello,

I have the impression that it works. However, I have occasionally had a mistake of this type:

```
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at me.kavin.piped.server.handlers.StreamHandlers.streamsResponse(StreamHandlers.java:132)
	at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$10(ServerLauncher.java:126)
	at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
	at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:249)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

I suppose it's not related to your addon, but it may be a piped timeout, but if in doubt I'd rather let you know.

thanks in any case!

Ps: just for my own information, why migrate to codeberg versus github?

**Comment by D01B0EB** [comment]
Hello,
You can inform Piped developers directly about server troubles on https://matrix.to/#/#piped:matrix.org.
Or just switch to another Piped or Invidious server. There are may be DOS attacks.

Concerning of Codeberg - to avoid forced github 2FA and another restrictions in the future. Codeberg also hosted by community instead of github, which obeys to commercial company.
